name: Build APK
on:
workflow_dispatch:
push:
branches: [ main ]
tags: ["v*"]

permissions:
contents: write

jobs:
build:
runs-on: ubuntu-latest
timeout-minutes: 30
steps:
- name: Checkout
uses: actions/checkout@v4
  - name: Setup Java 17
    uses: actions/setup-java@v4
    with:
      distribution: temurin
      java-version: 17

  - name: Setup Android SDK
    uses: android-actions/setup-android@v3

  - name: Install SDK packages
    run: |
      yes | sdkmanager --licenses
      sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"

  # Download Gradle and generate wrapper (more reliable)
  - name: Download Gradle 8.7
    run: |
      curl -sLo gradle-8.7-bin.zip https://services.gradle.org/distributions/gradle-8.7-bin.zip
      unzip -q gradle-8.7-bin.zip
      echo "$GITHUB_WORKSPACE/gradle-8.7/bin" >> $GITHUB_PATH

  - name: Generate Gradle wrapper
    run: |
      gradle wrapper --gradle-version 8.7
      chmod +x gradlew

  - name: Build debug APK
    run: |
      ./gradlew --version
      ./gradlew clean assembleDebug --stacktrace

  - name: Package APK
    run: |
      mkdir -p out
      cp app/build/outputs/apk/debug/app-debug.apk out/MediSuggester-debug.apk
      (sha256sum out/MediSuggester-debug.apk || shasum -a 256 out/MediSuggester-debug.apk) > out/SHA256.txt

  - name: Upload artifact (download from Actions)
    uses: actions/upload-artifact@v4
    with:
      name: MediSuggester-debug
      path: out/*

  - name: Publish GitHub Release (when you push a tag like v0.1.0)
    if: startsWith(github.ref, 'refs/tags/')
    uses: softprops/action-gh-release@v2
    with:
      files: |
        out/MediSuggester-debug.apk
        out/SHA256.txt
      name: MediSuggester ${{ github.ref_name }}
